# Generated by Django 5.2.8 on 2026-06-27 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_budgetcategory_symbol_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='icon',
            field=models.CharField(blank=True, default='utensils', max_length=50),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='symbol',
            field=models.CharField(blank=True, choices=[('utensils', 'Utensils'), ('car', 'Car'), ('shopping-cart', 'Shopping Cart'), ('film', 'Film'), ('home', 'Home'), ('heart-pulse', 'Healthcare'), ('fuel', 'Fuel'), ('wifi', 'Internet'), ('phone', 'Phone'), ('credit-card', 'Credit Card'), ('gift', 'Gift'), ('coffee', 'Coffee'), ('book', 'Education'), ('plane', 'Travel'), ('dumbbell', 'Fitness'), ('music', 'Music'), ('shirt', 'Shopping'), ('zap', 'Utilities'), ('piggy-bank', 'Savings'), ('briefcase', 'Work')], default='utensils', max_length=50),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('goal', 'Goal'), ('budget', 'Budget')], default='expense', max_length=20)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('icon', models.CharField(blank=True, default='utensils', max_length=50)),
                ('symbol', models.CharField(blank=True, choices=[('utensils', 'Utensils'), ('car', 'Car'), ('shopping-cart', 'Shopping Cart'), ('film', 'Film'), ('home', 'Home'), ('heart-pulse', 'Healthcare'), ('fuel', 'Fuel'), ('wifi', 'Internet'), ('phone', 'Phone'), ('credit-card', 'Credit Card'), ('gift', 'Gift'), ('coffee', 'Coffee'), ('book', 'Education'), ('plane', 'Travel'), ('dumbbell', 'Fitness'), ('music', 'Music'), ('shirt', 'Shopping'), ('zap', 'Utilities'), ('piggy-bank', 'Savings'), ('briefcase', 'Work')], default='utensils', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories',
                'indexes': [models.Index(fields=['user'], name='categories_user_id_1cc1e0_idx'), models.Index(fields=['type'], name='categories_type_735b1a_idx')],
                'unique_together': {('user', 'name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=50)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_made', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['transaction'], name='transaction_transac_a59b6e_idx'), models.Index(fields=['user'], name='transaction_user_id_325c3a_idx')],
            },
        ),
    ]
