# Generated by Django 5.2.15 on 2026-07-11 02:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_transaction_categor_45fcdd_idx_transaction_categor_bf503b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('budget_summary', 'Budget Summary'), ('monthly_report', 'Monthly Report'), ('category_analysis', 'Category Analysis'), ('spending_trends', 'Spending Trends'), ('complete', 'Complete Financial Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scheduled_reports',
                'indexes': [models.Index(fields=['user'], name='scheduled_r_user_id_469ede_idx'), models.Index(fields=['enabled'], name='scheduled_r_enabled_3e1867_idx'), models.Index(fields=['next_run'], name='scheduled_r_next_ru_163052_idx')],
            },
        ),
    ]
