# Generated by Django 5.2.8 on 2026-07-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_project_projectinvitation_projectmember_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alertsetting',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_accounts', to='api.project'),
        ),
        migrations.AddField(
            model_name='alert',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_alerts', to='api.project'),
        ),
        migrations.AddField(
            model_name='alertsetting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_alert_settings', to='api.project'),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_budget_categories', to='api.project'),
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_categories', to='api.project'),
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_expenses', to='api.project'),
        ),
        migrations.AddField(
            model_name='goal',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_goals', to='api.project'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_scheduled_reports', to='api.project'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_transactions', to='api.project'),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_transaction_history', to='api.project'),
        ),
        migrations.AlterUniqueTogether(
            name='alertsetting',
            unique_together={('user', 'project', 'setting_id')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('user', 'project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'project', 'name', 'type')},
        ),
    ]
