# Generated by Django 5.2.8 on 2026-07-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_alertsetting_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='category',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Bills', 'Bills'), ('Goals', 'Goals'), ('Security', 'Security'), ('Account', 'Account'), ('Investments', 'Investments'), ('Activity', 'Activity'), ('System', 'System'), ('AI', 'AI')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alertsetting',
            name='category',
            field=models.CharField(choices=[('Budget', 'Budget'), ('Bills', 'Bills'), ('Goals', 'Goals'), ('Security', 'Security'), ('Account', 'Account'), ('Investments', 'Investments'), ('Activity', 'Activity'), ('System', 'System'), ('AI', 'AI')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['dismissed'], name='alerts_dismiss_076291_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['priority'], name='alerts_priorit_9aa898_idx'),
        ),
    ]
