# Generated by Django 5.2.8 on 2026-07-17 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alert_dedup_key_alert_dismissed_alert_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset', models.CharField(default='transactions', max_length=50)),
                ('format', models.CharField(default='csv', max_length=10)),
                ('row_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_export_jobs', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='export_jobs_user_id_750c05_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('completed', 'Completed'), ('failed', 'Failed')], default='parsed', max_length=20)),
                ('format', models.CharField(blank=True, max_length=10)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.JSONField(blank=True, default=list)),
                ('total_rows', models.IntegerField(default=0)),
                ('valid_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_import_jobs', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='import_jobs_user_id_3a4715_idx')],
            },
        ),
        migrations.CreateModel(
            name='MappingTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mapping', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_mapping_templates', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mapping_templates',
                'indexes': [models.Index(fields=['user'], name='mapping_tem_user_id_dc4285_idx')],
                'unique_together': {('user', 'project', 'name')},
            },
        ),
    ]
