# Generated by Django 5.2.8 on 2026-07-17 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_exportjob_importjob_mappingtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=20)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Repeat every N frequency units.')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='0=Mon .. 6=Sun for weekly schedules.')),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly/yearly schedules.', null=True)),
                ('last_day_of_month', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('never_ends', models.BooleanField(default=True)),
                ('next_execution_date', models.DateField(blank=True, null=True)),
                ('last_execution_date', models.DateField(blank=True, null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_rules', to='api.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_rules', to='api.category')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_recurring_rules', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurring_rules',
            },
        ),
        migrations.CreateModel(
            name='RecurringExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_recurring_executions', to='api.project')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recutions', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_executions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.recurringrule')),
            ],
            options={
                'db_table': 'recurring_executions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['user'], name='recurring_r_user_id_add46f_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['status'], name='recurring_r_status_7a214b_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringrule',
            index=models.Index(fields=['next_execution_date'], name='recurring_r_next_ex_f49058_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexecution',
            index=models.Index(fields=['rule'], name='recurring_e_rule_id_96cf1c_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexecution',
            index=models.Index(fields=['user'], name='recurring_e_user_id_eec4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexecution',
            index=models.Index(fields=['scheduled_date'], name='recurring_e_schedul_e8d4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringexecution',
            index=models.Index(fields=['status'], name='recurring_e_status_974e51_idx'),
        ),
    ]
