# Generated by Django 5.2.15 on 2026-07-17 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recurringrule_recurringexecution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('strategy', models.CharField(choices=[('copy_exact', 'Copy Previous Budget Exactly'), ('copy_structure', 'Copy Category Structure Only'), ('reset_spent', 'Reset Spent to Zero'), ('carry_forward', 'Carry Forward Remaining Budget'), ('increase_percent', 'Increase Budget by Percentage'), ('decrease_percent', 'Decrease Budget by Percentage'), ('auto_adjust', 'Auto-Adjust from Previous Period')], default='copy_structure', max_length=30)),
                ('adjustment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('auto_carry_forward', models.BooleanField(default=False)),
                ('auto_adjust_previous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('interval', models.PositiveIntegerField(default=1, help_text='Repeat every N frequency units.')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='0=Mon .. 6=Sun for weekly schedules.')),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly/yearly schedules.', null=True)),
                ('last_day_of_month', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('never_ends', models.BooleanField(default=True)),
                ('next_generation_date', models.DateField(blank=True, null=True)),
                ('last_generation_date', models.DateField(blank=True, null=True)),
                ('generation_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anchor_budget', models.ForeignKey(blank=True, help_text='Budget used as the template source for copy strategies.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_anchor', to='api.budgetcategory')),
                ('last_generated_budget', models.ForeignKey(blank=True, help_text='FK placeholder; actual budget links live on executions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.recurringbudget')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_recurring_budgets', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurring_budgets',
            },
        ),
        migrations.CreateModel(
            name='RecurringBudgetExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_budgets', models.JSONField(blank=True, default=list, help_text='IDs of BudgetCategory rows created.')),
                ('scheduled_date', models.DateField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_recurring_budget_executions', to='api.project')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.recurringbudget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_budget_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recurring_budget_executions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringbudget',
            index=models.Index(fields=['user'], name='recurring_b_user_id_4ba278_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbudget',
            index=models.Index(fields=['status'], name='recurring_b_status_070818_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbudget',
            index=models.Index(fields=['next_generation_date'], name='recurring_b_next_ge_2824d3_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbudgetexecution',
            index=models.Index(fields=['rule'], name='recurring_b_rule_id_a5c6b1_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbudgetexecution',
            index=models.Index(fields=['user'], name='recurring_b_user_id_6c5ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbudgetexecution',
            index=models.Index(fields=['scheduled_date'], name='recurring_b_schedul_94888b_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringbudgetexecution',
            index=models.Index(fields=['status'], name='recurring_b_status_a54596_idx'),
        ),
    ]
