# Generated by Django 5.2.8 on 2026-07-18 08:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_recurringbudget_recurringbudgetexecution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialHealthScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('grade', models.CharField(default='F', max_length=2)),
                ('grade_label', models.CharField(default='Critical', max_length=20)),
                ('previous_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('flat', 'Flat')], default='flat', max_length=10)),
                ('dimensions', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'financial_health_scores',
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('budget_management', 'Budget Management'), ('cash_flow_stability', 'Cash Flow Stability'), ('savings_ratio', 'Savings Ratio'), ('income_stability', 'Income Stability'), ('expense_distribution', 'Expense Distribution'), ('spending_behaviour', 'Spending Behaviour'), ('goal_progress', 'Goal Progress'), ('financial_discipline', 'Financial Discipline'), ('recurring_commitments', 'Recurring Commitments'), ('risk_indicators', 'Risk Indicators')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('estimated_improvement', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_recommendations', to='api.project')),
                ('score_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.financialhealthscore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'health_recommendations',
                'ordering': ['-estimated_improvement'],
            },
        ),
        migrations.CreateModel(
            name='ScoreDimensionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimension', models.CharField(choices=[('budget_management', 'Budget Management'), ('cash_flow_stability', 'Cash Flow Stability'), ('savings_ratio', 'Savings Ratio'), ('income_stability', 'Income Stability'), ('expense_distribution', 'Expense Distribution'), ('spending_behaviour', 'Spending Behaviour'), ('goal_progress', 'Goal Progress'), ('financial_discipline', 'Financial Discipline'), ('recurring_commitments', 'Recurring Commitments'), ('risk_indicators', 'Risk Indicators')], max_length=40)),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.100'), max_digits=4)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_configs', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'score_dimension_configs',
            },
        ),
        migrations.AddIndex(
            model_name='financialhealthscore',
            index=models.Index(fields=['user', 'computed_at'], name='financial_h_user_id_1d44d2_idx'),
        ),
        migrations.AddIndex(
            model_name='financialhealthscore',
            index=models.Index(fields=['project', 'computed_at'], name='financial_h_project_8957a7_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecommendation',
            index=models.Index(fields=['user'], name='health_reco_user_id_442d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecommendation',
            index=models.Index(fields=['resolved'], name='health_reco_resolve_3ea997_idx'),
        ),
        migrations.AddIndex(
            model_name='scoredimensionconfig',
            index=models.Index(fields=['user'], name='score_dimen_user_id_38719e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scoredimensionconfig',
            unique_together={('user', 'project', 'dimension')},
        ),
    ]
