# Generated by Django 5.2.15 on 2026-07-18 10:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_financialhealthscore_healthrecommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_duplicate_groups', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'duplicate_groups',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium')], default='medium', max_length=10)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('resolution', models.CharField(choices=[('pending', 'Pending'), ('kept', 'Kept'), ('deleted', 'Deleted'), ('not_duplicate', 'Not a duplicate')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_of_matches', to='api.transaction')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.duplicategroup')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_duplicate_matches', to='api.project')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_matches', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'duplicate_matches',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('duplicate', 'Duplicate'), ('not_duplicate', 'Not a duplicate')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_duplicate_feedback', to='api.project')),
                ('transaction_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_as_a', to='api.transaction')),
                ('transaction_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_as_b', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'duplicate_feedback',
                'indexes': [models.Index(fields=['user', 'project'], name='duplicate_f_user_id_1035fe_idx')],
                'unique_together': {('user', 'project', 'transaction_a', 'transaction_b')},
            },
        ),
        migrations.AddIndex(
            model_name='duplicategroup',
            index=models.Index(fields=['user', 'status'], name='duplicate_g_user_id_18ab8d_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicategroup',
            index=models.Index(fields=['project', 'status'], name='duplicate_g_project_6ee20f_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicatematch',
            index=models.Index(fields=['user', 'project'], name='duplicate_m_user_id_d39a08_idx'),
        ),
        migrations.AddIndex(
            model_name='duplicatematch',
            index=models.Index(fields=['resolution'], name='duplicate_m_resolut_91c3de_idx'),
        ),
    ]
