# Generated by Django 5.2.15 on 2026-07-18 10:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_duplicategroup_duplicatematch_duplicatefeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('spending', 'Spending'), ('saving', 'Saving'), ('investment', 'Investment'), ('alert', 'Alert'), ('goal', 'Goal'), ('recurring', 'Recurring')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('dismissed', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insights',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', 'project', 'dismissed', 'generated_at'], name='insights_user_id_65506b_idx')],
            },
        ),
    ]
