# Generated by Django 5.2.15 on 2026-07-18 11:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant', models.CharField(max_length=255)),
                ('display_name', models.CharField(help_text='Human-friendly label.', max_length=255)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored'), ('converted', 'Converted')], default='detected', max_length=20)),
                ('cadence', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('avg_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('occurrences', models.PositiveIntegerField(default=0, help_text='Count of matched txns.')),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.category')),
                ('converted_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_subscriptions', to='api.recurringrule')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-monthly_cost', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant', models.CharField(max_length=255)),
                ('label', models.CharField(choices=[('ignored', 'Ignored'), ('confirmed', 'Confirmed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_feedback', to='api.project')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='api.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_feedback',
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'project', 'status', 'detected_at'], name='subscriptio_user_id_3239a9_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['dedup_key'], name='subscriptio_dedup_k_7d95cf_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionfeedback',
            index=models.Index(fields=['user', 'project', 'merchant'], name='subscriptio_user_id_98799d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionfeedback',
            unique_together={('user', 'project', 'merchant', 'label')},
        ),
    ]
