# Generated by Django 5.2.8 on 2026-07-22 14:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_subscription_subscriptionfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ml_model_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='predicted_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_transactions', to='api.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='prediction_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('deprecated', 'Deprecated')], default='candidate', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(blank=True, null=True)),
                ('model_path', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ml_model_versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['version'], name='ml_model_ve_version_5ad350_idx'), models.Index(fields=['status'], name='ml_model_ve_status_57c744_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_as_actual', to='api.category')),
                ('predicted_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_as_predicted', to='api.category')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_category_feedback', to='api.project')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_feedback', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'category_feedback',
                'indexes': [models.Index(fields=['user', 'project'], name='category_fe_user_id_c8df73_idx'), models.Index(fields=['transaction'], name='category_fe_transac_ec3c1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLTrainingSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('KAGGLE', 'Kaggle'), ('IMPORT', 'Import'), ('MANUAL', 'Manual'), ('FEEDBACK', 'Feedback')], max_length=20)),
                ('created_at', models.DateTimeField()),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at_db', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_samples', to='api.category')),
            ],
            options={
                'db_table': 'ml_training_samples',
                'indexes': [models.Index(fields=['source'], name='ml_training_source_7ae987_idx'), models.Index(fields=['category'], name='ml_training_categor_999e79_idx'), models.Index(fields=['created_at'], name='ml_training_created_58b22b_idx')],
                'unique_together': {('merchant', 'description', 'amount', 'transaction_type', 'category', 'source')},
            },
        ),
    ]
