# Generated by Django 5.2.8 on 2026-03-22 11:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('theme', models.CharField(default='system', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('wallet', 'Wallet'), ('cash', 'Cash')], max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('warning', 'Warning'), ('info', 'Info'), ('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('Budget', 'Budget'), ('Bills', 'Bills'), ('Goals', 'Goals'), ('Security', 'Security'), ('Account', 'Account'), ('Investments', 'Investments')], max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
        migrations.CreateModel(
            name='AlertSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Budget', 'Budget'), ('Bills', 'Bills'), ('Goals', 'Goals'), ('Security', 'Security'), ('Account', 'Account'), ('Investments', 'Investments')], max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('threshold_unit', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_settings',
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('budgeted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.CharField(max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Food & Dining', 'Food & Dining'), ('Transportation', 'Transportation'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Bills', 'Bills'), ('Healthcare', 'Healthcare'), ('Other', 'Other')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(max_length=500)),
                ('receipt_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('target_date', models.DateField()),
                ('category', models.CharField(choices=[('Emergency', 'Emergency'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Transportation', 'Transportation'), ('Education', 'Education'), ('Investment', 'Investment'), ('Other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'goals',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('Food & Dining', 'Food & Dining'), ('Transportation', 'Transportation'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Bills & Utilities', 'Bills & Utilities'), ('Healthcare', 'Healthcare'), ('Income', 'Income')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending')], default='completed', max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user'], name='accounts_user_id_6786b5_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user'], name='alerts_user_id_869dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['read'], name='alerts_read_3c6212_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['timestamp'], name='alerts_timesta_67be6b_idx'),
        ),
        migrations.AddIndex(
            model_name='alertsetting',
            index=models.Index(fields=['user'], name='alert_setti_user_id_bd7fcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alertsetting',
            unique_together={('user', 'setting_id')},
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['user'], name='budget_cate_user_id_f9fa7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user'], name='expenses_user_id_1a4067_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='expenses_date_a77b87_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user'], name='goals_user_id_9808c4_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['status'], name='goals_status_6bb941_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['target_date'], name='goals_target__152f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='transaction_user_id_b5bcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='transaction_date_7edf95_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='transaction_categor_45fcdd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='transaction_type_840495_idx'),
        ),
    ]
